### PR TITLE
Change tooltip appearance

### PR DESCRIPTION
**Pull request by rgmears**
Changes tooltip to black text on white background

### CODE REVIEW

**Comment by infograf768** [comment]
This PR changes all tabulations to spaces. Please reset the tabs. Then you have to Pull Request to joomla:staging

**Comment by infograf768** [comment]
Also, a lot of stuff has been deleted from the template.less (for example all the @import. This does not look OK.

**Comment by rgmears** [comment]
To make this I copied the template.less file from the staging branch of this website. Then compiled it with variables.less into the template.css file and uploaded all three files. The only changes I made were to the tooltips section. Any other changes came from the altered file here. In this regard I noticed that the blue background is gone on the Login page.

**Comment by rgmears** [comment]
I don't know how this happened, but the template.css file got pasted in the template.less file. that's why things are missing. When I tried to fix it, GitHub says I must be on a branch to do so.

**Comment by rgmears** [comment]
I'm confused. When I go to my branch &mdash; rgmears/joomla-cms. &mdash; I get this message: This branch is 19 commits behind joomla:staging. How do I update it?

And when I try to fix the template.less file GitHub says I must be on a branch, which as far as I can tell I am.

**Comment by rgmears** [comment]
The template.less file is fixed now. Shall I merge this or let you do it?

**Pull request merged**
